import { TetrisWord, DifficultyLevel } from './index';

export const normal: TetrisWord[] = [
  {
    id: "normal_1",
    word: "甲",
    kana: "こう",
    meaning: "1st in rank; shell",
    chineseMeaning: "甲",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "甲",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_2",
    word: "コーナー",
    kana: "コーナー",
    meaning: "corner",
    chineseMeaning: "角落",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "コーナー",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_3",
    word: "梢",
    kana: "こずえ",
    meaning: "treetop",
    chineseMeaning: "樹梢",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "梢",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_4",
    word: "コメント",
    kana: "コメント",
    meaning: "comment",
    chineseMeaning: "評論",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "コメント",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_5",
    word: "コンパス",
    kana: "コンパス",
    meaning: "compass",
    chineseMeaning: "指南針",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "コンパス",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_6",
    word: "財",
    kana: "ざい",
    meaning: "fortune, riches",
    chineseMeaning: "財富",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "財",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_7",
    word: "サイクル",
    kana: "サイクル",
    meaning: "cycle",
    chineseMeaning: "循環",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "サイクル",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_8",
    word: "サイズ",
    kana: "サイズ",
    meaning: "size",
    chineseMeaning: "尺寸",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "サイズ",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_9",
    word: "杯",
    kana: "さかずき",
    meaning: "wine cup",
    chineseMeaning: "酒杯",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "杯",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_10",
    word: "雑",
    kana: "ざつ",
    meaning: "rough, crude",
    chineseMeaning: "雜亂",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "雑",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_11",
    word: "さっと",
    kana: "さっと",
    meaning: "suddenly, smoothly",
    chineseMeaning: "迅速地",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "さっと",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_12",
    word: "侍",
    kana: "さむらい",
    meaning: "samurai",
    chineseMeaning: "武士",
    difficulty: "normal",
    category: "intermediate",
    jlptLevel: "n1",
    kanji: "侍",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_13",
    word: "酸",
    kana: "さん",
    meaning: "acid",
    chineseMeaning: "酸",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "酸",
    isKanji: true,
    complexity: 3
  },
  {
    id: "normal_14",
    word: "シート",
    kana: "シート",
    meaning: "seat; sheet",
    chineseMeaning: "座位、床單",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "シート",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_15",
    word: "ジーパン",
    kana: "ジーパン",
    meaning: "jeans",
    chineseMeaning: "牛仔褲",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ジーパン",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_16",
    word: "潮",
    kana: "しお",
    meaning: "tide",
    chineseMeaning: "潮汐",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "潮",
    isKanji: true,
    complexity: 3
  },
  {
    id: "normal_17",
    word: "ゲスト",
    kana: "ゲスト",
    meaning: "guest",
    chineseMeaning: "客人",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ゲスト",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_18",
    word: "獣",
    kana: "けだもの",
    meaning: "beast, brute",
    chineseMeaning: "野獸",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "獣",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_19",
    word: "決",
    kana: "けつ",
    meaning: "decision, vote",
    chineseMeaning: "決定",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "決",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_20",
    word: "けなす",
    kana: "けなす",
    meaning: "to speak ill of",
    chineseMeaning: "說壞話",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "けなす",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_21",
    word: "獣",
    kana: "けもの",
    meaning: "beast, brute",
    chineseMeaning: "野獸",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "獣",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_22",
    word: "トーン",
    kana: "トーン",
    meaning: "tone",
    chineseMeaning: "音調",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "トーン",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_23",
    word: "とっさに",
    kana: "とっさに",
    meaning: "at once",
    chineseMeaning: "瞬間",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "とっさに",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_24",
    word: "とって",
    kana: "とって",
    meaning: "handle, grip, knob",
    chineseMeaning: "把手",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "とって",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_25",
    word: "扉",
    kana: "とびら",
    meaning: "door, opening",
    chineseMeaning: "門扉",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "扉",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_26",
    word: "溝",
    kana: "どぶ",
    meaning: "ditch, drain, gap",
    chineseMeaning: "溝渠",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "溝",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_27",
    word: "富",
    kana: "とみ",
    meaning: "wealth, fortune",
    chineseMeaning: "財富",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "富",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_28",
    word: "ドライ",
    kana: "ドライ",
    meaning: "dry",
    chineseMeaning: "乾燥",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ドライ",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_29",
    word: "ドリル",
    kana: "ドリル",
    meaning: "drill",
    chineseMeaning: "鑽頭",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ドリル",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_30",
    word: "苗",
    kana: "なえ",
    meaning: "rice seedling",
    chineseMeaning: "幼苗",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "苗",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_31",
    word: "流し",
    kana: "ながし",
    meaning: "sink",
    chineseMeaning: "水槽",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "流し",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_32",
    word: "なにより",
    kana: "なにより",
    meaning: "most, best",
    chineseMeaning: "最重要的",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "なにより",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_33",
    word: "ナプキン",
    kana: "ナプキン",
    meaning: "napkin",
    chineseMeaning: "餐巾紙",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ナプキン",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_34",
    word: "荷",
    kana: "に",
    meaning: "load, baggage, cargo",
    chineseMeaning: "行李",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "荷",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_35",
    word: "にきび",
    kana: "にきび",
    meaning: "pimple, acne",
    chineseMeaning: "青春痘",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "にきび",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_36",
    word: "ニュー",
    kana: "ニュー",
    meaning: "new",
    chineseMeaning: "新的",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ニュー",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_37",
    word: "尿",
    kana: "にょう",
    meaning: "urine",
    chineseMeaning: "尿液",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "尿",
    isKanji: true,
    complexity: 3
  },
  {
    id: "normal_38",
    word: "主",
    kana: "ぬし",
    meaning: "owner, master, god",
    chineseMeaning: "主人",
    difficulty: "normal",
    category: "intermediate",
    jlptLevel: "n1",
    kanji: "主",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_39",
    word: "沼",
    kana: "ぬま",
    meaning: "swamp, bog, pond",
    chineseMeaning: "沼澤",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "沼",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_40",
    word: "ネガ",
    kana: "ネガ",
    meaning: "(photographic) negative",
    chineseMeaning: "底片",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ネガ",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_41",
    word: "ねだる",
    kana: "ねだる",
    meaning: "to nag, to demand",
    chineseMeaning: "糾纏",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ねだる",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_42",
    word: "刃",
    kana: "は",
    meaning: "blade, sword",
    chineseMeaning: "刀刃",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "刃",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_43",
    word: "パート",
    kana: "パート",
    meaning: "part-time job",
    chineseMeaning: "兼職",
    difficulty: "normal",
    category: "intermediate",
    jlptLevel: "n1",
    kanji: "パート",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_44",
    word: "いびき",
    kana: "いびき",
    meaning: "snoring",
    chineseMeaning: "打鼾",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "いびき",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_45",
    word: "未だ",
    kana: "いまだ",
    meaning: "yet, still",
    chineseMeaning: "尚未",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "未だ",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_46",
    word: "いやに",
    kana: "いやに",
    meaning: "awfully, terribly",
    chineseMeaning: "非常",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "いやに",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_47",
    word: "液",
    kana: "えき",
    meaning: "liquid, fluid",
    chineseMeaning: "液體",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "液",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_48",
    word: "襟",
    kana: "えり",
    meaning: "neck, collar",
    chineseMeaning: "領子",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "襟",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_49",
    word: "公",
    kana: "おおやけ",
    meaning: "public",
    chineseMeaning: "公開",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "公",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_50",
    word: "雄",
    kana: "おす",
    meaning: "male (animal)",
    chineseMeaning: "雄性",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "雄",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_51",
    word: "襲う",
    kana: "おそう",
    meaning: "to attack",
    chineseMeaning: "襲擊",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "襲う",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_52",
    word: "おだてる",
    kana: "おだてる",
    meaning: "to flatter",
    chineseMeaning: "奉承",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "おだてる",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_53",
    word: "乙",
    kana: "おつ",
    meaning: "2nd in rank",
    chineseMeaning: "乙",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "乙",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_54",
    word: "お袋",
    kana: "おふくろ",
    meaning: "mother",
    chineseMeaning: "母親",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "お袋",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_55",
    word: "おむつ",
    kana: "おむつ",
    meaning: "diaper, nappy",
    chineseMeaning: "尿布",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "おむつ",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_56",
    word: "折",
    kana: "おり",
    meaning: "chance, occasion",
    chineseMeaning: "機會",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "折",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_57",
    word: "我",
    kana: "が～",
    meaning: "ego",
    chineseMeaning: "自我",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "我",
    isKanji: true,
    complexity: 3
  },
  {
    id: "normal_58",
    word: "ガイド",
    kana: "ガイド",
    meaning: "guide",
    chineseMeaning: "導遊",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ガイド",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_59",
    word: "かかと",
    kana: "かかと",
    meaning: "shoe heel",
    chineseMeaning: "腳跟",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "かかと",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_60",
    word: "カクテル",
    kana: "カクテル",
    meaning: "cocktail",
    chineseMeaning: "雞尾酒",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "カクテル",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_61",
    word: "崖",
    kana: "がけ",
    meaning: "cliff",
    chineseMeaning: "懸崖",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "崖",
    isKanji: true,
    complexity: 3
  },
  {
    id: "normal_62",
    word: "かさばる",
    kana: "かさばる",
    meaning: "to be bulky",
    chineseMeaning: "佔體積",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "かさばる",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_63",
    word: "頭",
    kana: "かしら",
    meaning: "head, chief",
    chineseMeaning: "頭",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "頭",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_64",
    word: "且つ",
    kana: "かつ",
    meaning: "yet, and",
    chineseMeaning: "而且",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "且つ",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_65",
    word: "がっくり",
    kana: "がっくり",
    meaning: "heartbroken",
    chineseMeaning: "心碎",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "がっくり",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_66",
    word: "カット",
    kana: "カット",
    meaning: "cut, cutting",
    chineseMeaning: "剪切",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "カット",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_67",
    word: "粥",
    kana: "かゆ",
    meaning: "rice porridge",
    chineseMeaning: "粥",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "粥",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_68",
    word: "キャッチ",
    kana: "キャッチ",
    meaning: "catch",
    chineseMeaning: "接住",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "キャッチ",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_69",
    word: "強",
    kana: "きょう",
    meaning: "strong",
    chineseMeaning: "強",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "強",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_70",
    word: "クイズ",
    kana: "クイズ",
    meaning: "quiz",
    chineseMeaning: "測驗",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "クイズ",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_71",
    word: "茎",
    kana: "くき",
    meaning: "stalk",
    chineseMeaning: "莖",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "茎",
    isKanji: true,
    complexity: 3
  },
  {
    id: "normal_72",
    word: "嘴",
    kana: "くちばし",
    meaning: "beak, bill",
    chineseMeaning: "鳥嘴",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "嘴",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_73",
    word: "ぐっと",
    kana: "ぐっと",
    meaning: "firmly, fast, more",
    chineseMeaning: "牢牢",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ぐっと",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_74",
    word: "蔵",
    kana: "くら",
    meaning: "warehouse, cellar",
    chineseMeaning: "倉庫",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "蔵",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_75",
    word: "グレー",
    kana: "グレー",
    meaning: "grey, gray",
    chineseMeaning: "灰色",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "グレー",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_76",
    word: "クレーン",
    kana: "クレーン",
    meaning: "crane",
    chineseMeaning: "起重機",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "クレーン",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_77",
    word: "胴",
    kana: "どう",
    meaning: "trunk, body, frame",
    chineseMeaning: "身軀",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "胴",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_78",
    word: "軸",
    kana: "じく",
    meaning: "axis, stem, shaft",
    chineseMeaning: "軸",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "軸",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_79",
    word: "雫",
    kana: "しずく",
    meaning: "drop (of water)",
    chineseMeaning: "水滴",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "雫",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_80",
    word: "システム",
    kana: "システム",
    meaning: "system",
    chineseMeaning: "系統",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "システム",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_81",
    word: "垢",
    kana: "あか",
    meaning: "dirt, filth",
    chineseMeaning: "污垢",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "垢",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_82",
    word: "顎",
    kana: "あご",
    meaning: "chin",
    chineseMeaning: "下巴",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "顎",
    isKanji: true,
    complexity: 3
  },
  {
    id: "normal_83",
    word: "麻",
    kana: "あさ",
    meaning: "hemp",
    chineseMeaning: "麻",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "麻",
    isKanji: true,
    complexity: 3
  },
  {
    id: "normal_84",
    word: "あざ",
    kana: "あざ",
    meaning: "birthmark, bruise",
    chineseMeaning: "痣",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "あざ",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_85",
    word: "網",
    kana: "あみ",
    meaning: "net",
    chineseMeaning: "網",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "網",
    isKanji: true,
    complexity: 3
  },
  {
    id: "normal_86",
    word: "甲",
    kana: "こう",
    meaning: "1st in rank; shell",
    chineseMeaning: "甲",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "甲",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_87",
    word: "コーナー",
    kana: "コーナー",
    meaning: "corner",
    chineseMeaning: "角落",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "コーナー",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_88",
    word: "梢",
    kana: "こずえ",
    meaning: "treetop",
    chineseMeaning: "樹梢",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "梢",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_89",
    word: "コメント",
    kana: "コメント",
    meaning: "comment",
    chineseMeaning: "評論",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "コメント",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_90",
    word: "コンパス",
    kana: "コンパス",
    meaning: "compass",
    chineseMeaning: "指南針",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "コンパス",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_91",
    word: "財",
    kana: "ざい",
    meaning: "fortune, riches",
    chineseMeaning: "財富",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "財",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_92",
    word: "サイクル",
    kana: "サイクル",
    meaning: "cycle",
    chineseMeaning: "循環",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "サイクル",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_93",
    word: "サイズ",
    kana: "サイズ",
    meaning: "size",
    chineseMeaning: "尺寸",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "サイズ",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_94",
    word: "杯",
    kana: "さかずき",
    meaning: "wine cup",
    chineseMeaning: "酒杯",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "杯",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_95",
    word: "雑",
    kana: "ざつ",
    meaning: "rough, crude",
    chineseMeaning: "雜亂",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "雑",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_96",
    word: "さっと",
    kana: "さっと",
    meaning: "suddenly, smoothly",
    chineseMeaning: "迅速地",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "さっと",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_97",
    word: "侍",
    kana: "さむらい",
    meaning: "samurai",
    chineseMeaning: "武士",
    difficulty: "normal",
    category: "intermediate",
    jlptLevel: "n1",
    kanji: "侍",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_98",
    word: "酸",
    kana: "さん",
    meaning: "acid",
    chineseMeaning: "酸",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "酸",
    isKanji: true,
    complexity: 3
  },
  {
    id: "normal_99",
    word: "シート",
    kana: "シート",
    meaning: "seat; sheet",
    chineseMeaning: "座位、床單",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "シート",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_100",
    word: "ジーパン",
    kana: "ジーパン",
    meaning: "jeans",
    chineseMeaning: "牛仔褲",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ジーパン",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_101",
    word: "潮",
    kana: "しお",
    meaning: "tide",
    chineseMeaning: "潮汐",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "潮",
    isKanji: true,
    complexity: 3
  },
  {
    id: "normal_102",
    word: "ゲスト",
    kana: "ゲスト",
    meaning: "guest",
    chineseMeaning: "客人",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ゲスト",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_103",
    word: "獣",
    kana: "けだもの",
    meaning: "beast, brute",
    chineseMeaning: "野獸",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "獣",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_104",
    word: "決",
    kana: "けつ",
    meaning: "decision, vote",
    chineseMeaning: "決定",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "決",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_105",
    word: "けなす",
    kana: "けなす",
    meaning: "to speak ill of",
    chineseMeaning: "說壞話",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "けなす",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_106",
    word: "獣",
    kana: "けもの",
    meaning: "beast, brute",
    chineseMeaning: "野獸",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "獣",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_107",
    word: "トーン",
    kana: "トーン",
    meaning: "tone",
    chineseMeaning: "音調",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "トーン",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_108",
    word: "とっさに",
    kana: "とっさに",
    meaning: "at once",
    chineseMeaning: "瞬間",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "とっさに",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_109",
    word: "とって",
    kana: "とって",
    meaning: "handle, grip, knob",
    chineseMeaning: "把手",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "とって",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_110",
    word: "扉",
    kana: "とびら",
    meaning: "door, opening",
    chineseMeaning: "門扉",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "扉",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_111",
    word: "溝",
    kana: "どぶ",
    meaning: "ditch, drain, gap",
    chineseMeaning: "溝渠",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "溝",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_112",
    word: "富",
    kana: "とみ",
    meaning: "wealth, fortune",
    chineseMeaning: "財富",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "富",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_113",
    word: "ドライ",
    kana: "ドライ",
    meaning: "dry",
    chineseMeaning: "乾燥",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ドライ",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_114",
    word: "ドリル",
    kana: "ドリル",
    meaning: "drill",
    chineseMeaning: "鑽頭",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ドリル",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_115",
    word: "苗",
    kana: "なえ",
    meaning: "rice seedling",
    chineseMeaning: "幼苗",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "苗",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_116",
    word: "流し",
    kana: "ながし",
    meaning: "sink",
    chineseMeaning: "水槽",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "流し",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_117",
    word: "なにより",
    kana: "なにより",
    meaning: "most, best",
    chineseMeaning: "最重要的",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "なにより",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_118",
    word: "ナプキン",
    kana: "ナプキン",
    meaning: "napkin",
    chineseMeaning: "餐巾紙",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ナプキン",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_119",
    word: "荷",
    kana: "に",
    meaning: "load, baggage, cargo",
    chineseMeaning: "行李",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "荷",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_120",
    word: "にきび",
    kana: "にきび",
    meaning: "pimple, acne",
    chineseMeaning: "青春痘",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "にきび",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_121",
    word: "ニュー",
    kana: "ニュー",
    meaning: "new",
    chineseMeaning: "新的",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ニュー",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_122",
    word: "尿",
    kana: "にょう",
    meaning: "urine",
    chineseMeaning: "尿液",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "尿",
    isKanji: true,
    complexity: 3
  },
  {
    id: "normal_123",
    word: "主",
    kana: "ぬし",
    meaning: "owner, master, god",
    chineseMeaning: "主人",
    difficulty: "normal",
    category: "intermediate",
    jlptLevel: "n1",
    kanji: "主",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_124",
    word: "沼",
    kana: "ぬま",
    meaning: "swamp, bog, pond",
    chineseMeaning: "沼澤",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "沼",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_125",
    word: "ネガ",
    kana: "ネガ",
    meaning: "(photographic) negative",
    chineseMeaning: "底片",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ネガ",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_126",
    word: "ねだる",
    kana: "ねだる",
    meaning: "to nag, to demand",
    chineseMeaning: "糾纏",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "ねだる",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_127",
    word: "刃",
    kana: "は",
    meaning: "blade, sword",
    chineseMeaning: "刀刃",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "刃",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_128",
    word: "パート",
    kana: "パート",
    meaning: "part-time job",
    chineseMeaning: "兼職",
    difficulty: "normal",
    category: "intermediate",
    jlptLevel: "n1",
    kanji: "パート",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_129",
    word: "いびき",
    kana: "いびき",
    meaning: "snoring",
    chineseMeaning: "打鼾",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "いびき",
    isKanji: false,
    complexity: 3
  },
  {
    id: "normal_130",
    word: "未だ",
    kana: "いまだ",
    meaning: "yet, still",
    chineseMeaning: "尚未",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "未だ",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_131",
    word: "いやに",
    kana: "いやに",
    meaning: "awfully, terribly",
    chineseMeaning: "非常",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "いやに",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_132",
    word: "液",
    kana: "えき",
    meaning: "liquid, fluid",
    chineseMeaning: "液體",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "液",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_133",
    word: "襟",
    kana: "えり",
    meaning: "neck, collar",
    chineseMeaning: "領子",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "襟",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_134",
    word: "公",
    kana: "おおやけ",
    meaning: "public",
    chineseMeaning: "公開",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "公",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_135",
    word: "雄",
    kana: "おす",
    meaning: "male (animal)",
    chineseMeaning: "雄性",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "雄",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_136",
    word: "襲う",
    kana: "おそう",
    meaning: "to attack",
    chineseMeaning: "襲擊",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "襲う",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_137",
    word: "おだてる",
    kana: "おだてる",
    meaning: "to flatter",
    chineseMeaning: "奉承",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "おだてる",
    isKanji: false,
    complexity: 4
  },
  {
    id: "normal_138",
    word: "乙",
    kana: "おつ",
    meaning: "2nd in rank",
    chineseMeaning: "乙",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "乙",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_139",
    word: "お袋",
    kana: "おふくろ",
    meaning: "mother",
    chineseMeaning: "母親",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "お袋",
    isKanji: true,
    complexity: 4
  },
  {
    id: "normal_140",
    word: "おむつ",
    kana: "おむつ",
    meaning: "diaper, nappy",
    chineseMeaning: "尿布",
    difficulty: "normal",
    category: "jlpt",
    jlptLevel: "n1",
    kanji: "おむつ",
    isKanji: false,
    complexity: 4
  }
];
